### ISSUE TITLE
Cannot run GameServerConsole with redis on local machine

### ISSUE THREAD

**Issue by nubonics** [MiscellaneousStuff/LeagueSandbox-RL-Learning#2]
```
C:\Users\Sylar6\PycharmProjects\LeagueSandbox-RL-Learning\GameServerConsole\bin\Debug\netcoreapp3.0>GameServerConsole.exe --redis_port "6379"
[2022-04-29 21:04:47,066] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package LeagueSandbox-Scripts does not contain Items, skipping...
[2022-04-29 21:04:47,079] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package LeagueSandbox-Scripts does not contain Maps, skipping...
[2022-04-29 21:04:47,079] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package LeagueSandbox-Scripts does not contain Spells, skipping...
[2022-04-29 21:04:47,079] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package LeagueSandbox-Scripts does not contain Stats, skipping...
[2022-04-29 21:04:47,081] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package: LeagueSandbox-Scripts does not contain any items, skipping...
[2022-04-29 21:04:48,141] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Loaded all C# scripts from package: LeagueSandbox-Scripts
[2022-04-29 21:04:48,141] [1] DEBUG LeagueSandbox.GameServer.Content.ContentManager - Loaded package with name: LeagueSandbox-Scripts
[2022-04-29 21:04:48,142] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package LeagueSandbox-Default does not contain Champions, skipping...
[2022-04-29 21:04:48,166] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package LeagueSandbox-Default does not contain Buffs, skipping...
[2022-04-29 21:04:48,626] [1] DEBUG LeagueSandbox.GameServer.Content.Package - LeagueSandbox-Default does not have C# scripts, skipping...
[2022-04-29 21:04:48,626] [1] DEBUG LeagueSandbox.GameServer.Content.ContentManager - Loaded package with name: LeagueSandbox-Default
[2022-04-29 21:04:48,627] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package LeagueSandbox-AI does not contain Champions, skipping...
[2022-04-29 21:04:48,627] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package LeagueSandbox-AI does not contain Items, skipping...
[2022-04-29 21:04:48,627] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package LeagueSandbox-AI does not contain Buffs, skipping...
[2022-04-29 21:04:48,628] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package LeagueSandbox-AI does not contain Maps, skipping...
[2022-04-29 21:04:48,628] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package LeagueSandbox-AI does not contain Spells, skipping...
[2022-04-29 21:04:48,628] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package LeagueSandbox-AI does not contain Stats, skipping...
[2022-04-29 21:04:48,629] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Package: LeagueSandbox-AI does not contain any items, skipping...
[2022-04-29 21:04:48,685] [1] DEBUG LeagueSandbox.GameServer.Content.Package - Loaded all C# scripts from package: LeagueSandbox-AI
[2022-04-29 21:04:48,685] [1] DEBUG LeagueSandbox.GameServer.Content.ContentManager - Loaded package with name: LeagueSandbox-AI
[2022-04-29 21:04:48,689] [1] DEBUG LeagueSandbox.GameServer.Server - League Sandbox Build 05/04/2042 09:32:29 UTC
[2022-04-29 21:04:48,690] [1] DEBUG LeagueSandbox.GameServer.Server - Yorick 0.2.0
[2022-04-29 21:04:48,690] [1] INFO LeagueSandbox.GameServer.Server - Game started on port: 5119
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at ENet.Native.enet_address_set_host(ENetAddress& address, Byte[] hostName)
   at ENet.Address.SetHost(String hostName)
   at PacketDefinitions420.PacketServer.InitServer(String host, UInt16 port, Dictionary`2 blowfishKeys, IGame game, NetworkHandler`1 netReq, NetworkHandler`1 netResp) in C:\Users\Sylar6\PycharmProjects\LeagueSandbox-RL-Learning\PacketDefinitions420\PacketServer.cs:line 33
   at LeagueSandbox.GameServer.Server.Start() in C:\Users\Sylar6\PycharmProjects\LeagueSandbox-RL-Learning\GameServerLib\Server.cs:line 46
   at LeagueSandbox.GameServer.GameServerLauncher..ctor(String serverHost, UInt16 serverPort, String configJson, String blowfishKey, Int32 human_count, Int32 agent_count, Single multiplier, String replay_path, UInt16 redis_port, Single step_multiplier) in C:\Users\Sylar6\PycharmProjects\LeagueSandbox-RL-Learning\GameServerLib\Program.cs:line 41
   at LeagueSandbox.GameServerConsole.Program.Main(String[] args) in C:\Users\Sylar6\PycharmProjects\LeagueSandbox-RL-Learning\GameServerConsole\Program.cs:line 30
```

**Comment by osayes** [comment]
Met the same issue, had you solved the issue?
